### ISSUE TITLE
Breaks for Fish-Shell users [c122a06]

### ISSUE THREAD

**Issue by JacobTravers** [alexherbo2/alacritty.kak#3]
This commit https://github.com/alexherbo2/alacritty.kak/commit/c122a06c07682b47b895f821727a92a360bcc07f seems to break alacritty.kak when using fish-shell

**Comment by kkga** [comment]
@JacobTravers I'm also having problems in fish. Looks like the environment isn't sourced properly after after the mentioned commit. Were you able to resolve this?

**Comment by JacobTravers** [comment]
@kkga no, for now I set plug.kak to use the previous commit.

**Comment by JacobTravers** [comment]
@kkga I realized this was an issue because I was using the AUR "alacritty-ligatures-git" package which is a few releases behind main, testing with normal alacritty seems to work on my machine.
